### ISSUE TITLE
Task 'dbReverseEngineer' not found in root project 'Test_v3'.

### ISSUE THREAD

**Issue by sanjaykharwar** [grails-plugins/grails-db-reverse-engineer#9]
I am not able to create domain class after running "gradlew dbReverseEngineer" command in command promp.

**My Environment**:
Grails Version: 3.1.0
Groovy Version: 2.4.5
JVM Version: 1.7.0_79

I am getting following error while creating domain class...
FAILURE: Build failed with an exception.
- What went wrong:
  Task '**dbReverseEngineer**' not found in root project 'Test_v3'.
- Try:
  Run gradlew tasks to get a list of available tasks. Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.execution.TaskSelectionException: Task 'dbReverseEngineer' not found in root project 'Test_v3'.
      at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
      at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
      at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
      at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
      at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
      at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
      at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
      at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLauncher.java:143)
      at org.gradle.internal.Factories$1.create(Factories.java:22)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
      at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
      at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
      at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
      at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
      at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
      at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
      at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
      at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
      at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:33)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
      at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by kumik** [comment]
Please make sure that you have added the plugin to your classpath, both for buildscript dependencies and project dependencies.

Thus:

``` groovy
buildscript {
    dependencies {
        classpath 'org.grails.plugins:db-reverse-engineer:4.0.0'
    }
}
dependencies {
        classpath 'org.grails.plugins:db-reverse-engineer:4.0.0'
}
```

**Comment by sanjaykharwar** [comment]
This is not working for me... I got following error message....I have attached my **build.gradle** file
In My file I am using following setting for **project dependencies**
dependencies {
        **compile** 'org.grails.plugins:db-reverse-engineer:4.0.0'
}

`C:\Users\XXX\git\Test_v3>gradlew dbReverseEngineer

FAILURE: Build failed with an exception.
[build.gradle.txt](https://github.com/grails-plugins/grails-db-reverse-engineer/files/266026/build.gradle.txt)
- Where:
  Build file 'C:\Users\XXX\git\Test_v3\build.gradle' line: 87
- What went wrong:
  A problem occurred evaluating root project 'Test_v3'.
  
  > Could not find method classpath() for arguments [org.grails.plugins:db-reverse-engineer:4.0.0] on root project 'Test_v3'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

**Comment by gmborisov** [comment]
I have the same problem.
grailsVersion=3.1.5
gradleWrapperVersion=2.9

**Comment by aaaia** [comment]
Same problem. 
In maven repo plugin is not compiled (zip format). 
Unfortunately cannot compile plugin due to errors.
